<?php

/**
 * @file
 * Provides Hover Card for all user links with "username" as their class.
 */

/**
 * The minimum version of Hover Card required.
 */
define('HOVER_CARD_MIN_PLUGIN_VERSION', '1.0');

/**
 * Implements hook_init().
 */
function hover_card_init() {
  // Declaring Variables.
  $hover_card = 'hover_card';
  $module_path = drupal_get_path('module', 'hover_card');

  // Initializing the Hover Card Plugin from Libraries.
  libraries_load($hover_card);

  // Adding CSS.
  drupal_add_css($module_path . '/stylesheets/hover_card.css');

  // Adding JS.
  drupal_add_js($module_path . '/javascripts/hover_card.js');
  drupal_add_js(array($hover_card => array('module_path' => $module_path)), array('type' => 'setting', 'scope' => JS_DEFAULT));
}

/**
 * Implements hook_libraries_info().
 */
function hover_card_libraries_info() {
  $libraries['hover_card'] = array(
    'name' => 'Hover Card Plugin',
    'vendor url' => 'http://designwithpc.com/Plugins/Hovercard',
    'download url' => 'https://github.com/prashantchaudhary/hovercard/archive/master.zip',
    'version arguments' => array(
      'file' => 'jquery.hovercard.js',
      'pattern' => '@[\s\S]*(?<=Version )([0-9.]+)@',
    ),
    'files' => array(
      'js' => array(
        'jquery.hovercard.min.js',
      ),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_menu().
 */
function hover_card_menu() {
  $items['hover-card/%user'] = array(
    'title' => 'Hover Card',
    'page callback' => 'hover_card',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hover_card().
 *
 * Here we'll fetch the values from $_GET[] request and then using json_encode()
 * we'll encode those values.
 */
function hover_card($user_fields) {
  $picture = array();

  if (isset($user_fields->name) && !empty($user_fields->name)) {
    $name = $user_fields->name;
  }

  if (isset($user_fields->mail) && !empty($user_fields->mail)) {
    $mail = $user_fields->mail;
  }

  if (isset($user_fields->picture->uri) && !empty($user_fields->picture->uri)) {
    $picture  = theme('image_style', array(
      'style_name' => 'thumbnail',
      'path' => $user_fields->picture->uri,
     )
    );
  }

  foreach ($user_fields->roles as $key => $value) {
    if ($key != 2) {
      $roles = ($value);
    }
  }

  $array = array(
    'name' => $name,
    'mail' => $mail,
    'picture' => $picture,
    'roles' => $roles,
  );

  return theme('hover_card_template', array('details' => $array));
}

/**
 * Implements hook_theme().
 *
 * Render some basic output for this module.
 */
function hover_card_theme($existing, $type, $theme, $path) {
  return array(
    'hover_card_template' => array(
      'render element' => 'elements',
      'template' => '/templates/hover-card-template',
    ),
  );
}
