<?php

/**
 * @file
 * Provides Hover Card for all user links with "username" as their class.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function hover_card_help($route_name, RouteMatchInterface $route_match) {
  global $base_url;
  switch ($route_name) {
    case 'help.page.hover_card':
      $output = '';
      $output .= '<p>' . t('Hovercard is a module which is based on <a href="@hovercard">hovercard</a> which is a free light weight jQuery plugin that enables you to display related information with the hovered label, link, or any html element of your choice. This module extends Drupal to provide Hovercard for the users of the website.', array('@hovercard' => 'http://designwithpc.com/Plugins/Hovercard')) . '</p>';
      $output .= '<h6>' . t('Dependencies') . '</h6>';
      $output .= '<ul>';
      $output .= t('<li><a href="@libraries">Libraries API 2</a></li>', array('@libraries' => 'https://drupal.org/project/libraries'));
      $output .= '</ul>';
      $output .= '<h6>' . t('Installation') . '</h6>';
      $output .= '<p>' . t('The Hover Card module is very similar to other Drupal modules which requires Libraries Module to use for the 3rd party code integration. Hence, for installation of the Hover Card module please follow the below mentioned steps:') . '</p>';
      $output .= '<ol>';
      $output .= t('<li>Install as usual, see <a href="@1294804">https://www.drupal.org/node/1294804</a> for further information.</li>', array('@1294804' => 'https://www.drupal.org/node/1294804'));
      $output .= '<li>' . t('Download and install the Libraries Module - 2.x and after the module installation create a new folder called <code>libraries</code> under your <code>sites/all/</code> folder. (Creating this folder will help us to locate our 3rd party code integration.)') . '</li>';
      $output .= '<li>' . t('Download the compressed version of jQuery <a href="@github">Hovercard Plugin</a> and extract the files into <code>/libraries/hover_card/</code>', array('@github' => 'https://github.com/prashantchaudhary/hovercard/archive/master.zip')) . '</li>';
      $output .= '<li>' . t('Now, in your <code>/modules/contrib/</code> directory, download the <a href="@project_page">Hover Card</a> module.', array('@project_page' => 'https://www.drupal.org/project/hover_card')) . '</li>';
      $output .= '<li>' . t('Enable the Hover Card module.') . '</li>';
      $output .= '</ol>';
      $output .= '<h6>' . t('Configuration') . '</h6>';
      $output .= '<ul>';
      $output .= '<li>' . t('After enabling it please check your <a href="@status">Status Report</a> where there should be a new option showing <code>Hover Card Plugin - v1.0 installed</code> with a success (green) status.', array('@status' => $base_url . '/admin/reports/status')) . '</p>';
      $output .= '<li>' . t('This module has no menu or modifiable settings. There is no configuration. When enabled and configured properly, this module will display the hover card to the user links with <code>username</code> as class to their anchor tags. To disable the hover card from user links, disable the module and clear caches.') . '</p>';
      $output .= '</ul>';

      return $output;
  }
}

/**
 * Implements hook_page_attachments()
 */
function hover_card_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'hover_card/hover_card';
  $page['#attached']['drupalSettings']['module_path'] = drupal_get_path('module', 'hover_card');;
}

/**
 * Page callback; Initiates when 'hover-card/%user' path is accessed.
 *
 * @param string $html
 * Prints the values at the requested menu, such as hover-card/1.
 * @todo Find D8 way for this!
 */
function hover_card_ajax_callback($html) {
  // AJAX output.
  print $html;
  drupal_page_footer();
}

/**
 * Implements hook_theme().
 *
 * This will render some basic output for this module.
 */
function hover_card_theme($existing, $type, $theme, $path) {
  return array(
    'hover_card_template' => array(
      'variables' => array('details' => NULL),
      'template' => 'hover-card',
    ),
  );
}
